# Generated by Django 2.0.6 on 2018-06-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_app', '0002_auto_20180613_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='date_formed',
        ),
        migrations.AddField(
            model_name='band',
            name='year_formed',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
