# Generated by Django 2.0.6 on 2018-06-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_app', '0003_auto_20180613_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='release_date',
        ),
        migrations.AddField(
            model_name='album',
            name='release_year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
